### PR TITLE
Delete experimental FROST stub code

### PR DESCRIPTION
**Pull request by hdevalence**
This makes the crate publishable.

### CODE REVIEW

**Comment by hdevalence** [comment]
I don't have publish access to crates.io.

@redshiftzero Could you merge this and publish as 0.9.0, so that it unblocks https://github.com/penumbra-zone/penumbra/pull/3289 which should use `sign_deterministic`?

**Comment by cronokirby** [comment]
Actually, the need to add Serialize was on the `Decaf377Rdsa` struct, which this change deletes. I don't think commit f47c63d is necessary.

**Comment by redshiftzero** [comment]
Invited you both @cronokirby @hdevalence as owners of the `decaf377-rdsa` crate (holding off on doing a release until we snip out f47c63d3e9d029df4b2becd814be7c8a8f9d5838)

**Comment by hdevalence** [comment]
We don't need to snip it out, could we please get this released and tagged so we can unblock other work?

**Comment by redshiftzero** [comment]
Published: https://crates.io/crates/decaf377-rdsa/0.9.0

**Pull request merged**
